language: node_js
sudo: required
dist: trusty
services:
  - docker
matrix:
  include:
    - node_js: 6.9.4
    - node_js: 7.10.1
    - node_js: 8.11.4
    - node_js: 10.9.0
    - node_js: 6.9.4
      env: INTEGRATION=true
before_install:
  - npm install -g npm@'>=2.13.5'
script:
  - |
    git config --global user.name "Travis CI"
    git config --global user.email "devops@digitalbits.io"
    if [ "${SAUCE}" = "true" ]; then
      if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
        gulp test:sauce
      else
        echo "Pull request - skip Sauce Labs testing..."
      fi
      #elif [ "${INTEGRATION}" = "true" ]; then
      # Ugly but it's the only way to make istanbul generate coverage report
      #babel-node ./node_modules/gulp/bin/gulp.js test:integration
    else
      gulp test:unit
    fi
after_success:
  - |
    # Send report to coveralls but only once
    if [ "${INTEGRATION}" = "true" ] && [ "${TRAVIS_BRANCH}" = "master" ] ; then
      gulp submit-coverage
    fi
env:
  global:
  - secure: Pc3DwkXywnOGAhUdBZiUCKjyljzrQzPoqm9EEr+UL2BaeaDniFLCLEkuU+ViiuJBo8oPyOIl7I+d86Mi5q06fQx55+xH7DmiW/aj4qKVB2U6Ghn6A3QWkQuvRB1o8SP7iTYRCX480ULZs6AGrMd9y1PFRx/L93fBrO+J/bOtEmg=
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
notifications:
  email: false
  slack:
    secure: Pg+/xv8os+DDCCLTkdNFqIrb6z7T4Z5YWKu/Q2TXQJplMfyNavzJ2nJcm+Ka2vwL8oCONgt/y3PMw8O4jTn9gcza2Hal2G+Ubyi7tvjEekYsv8vtkwr1cnadRPQeBJn3xXha8ZcNZLMijwzzmB+DccTkqpi1hXfGCZNf0HrngFhA1AChMik89KuuqdczgipUPvz1+3LjCuX7eoQUhx+2/YbAc9T7mYZIgeG2p9HbxEva9O7Qp/XLWnXtXIUTuUswh/Hc+SZKcB+7E5cnpQO8vsLvg8/jeAOw0UXJemMyZSSUq07HrHfv4qK1A1NF7K6FVje469rg9gsA/7T0N/YhxCa7omrfvBFe/wydVCM5x3nKQ9RqNJSTHf5/fAzR//3W7ftZGqVZ4PtnmWKPypmG61utPbQ7+OMCphqXZhu84PAqzcqCLleBZFRBuqWZjXRqyBKaYYG0H4LYPSYfFs1lsqxofG3krGLXYDOs68aE+jLFGQxHhoCqrEcNEQEfTng6BzCQ2xqS9j+x/TpiScgYFp3/C4/bwea4ioBAGNt9/yyCJeNM2+RO2XvOjeknVe7kBECA/VDhKY1YsjOrOlkn+T+5aZmOxNLlcNTpmoub1s0eHptXb809xrKMy6shcjSsmnBgQ1/3wY61ZjnA9Ufue5R66Hw7fPaTmZvC8hzE7Qo=
before_deploy: gulp build
after_deploy: "./after_deploy.sh"
deploy:
  - provider: npm
    email: devops@digitalbits.io
    api_key: "$NPM_TOKEN"
    skip_cleanup: true
    on:
      tags: true
      repo: DigitalBitsOrg/js-digitalbits-sdk
      node: 6.9.4
      condition: "$INTEGRATION = true"
  - provider: script
    script: "./bower_publish.sh"
    skip_cleanup: true
    on:
      tags: true
      repo: DigitalBitsOrg/js-digitalbits-sdk
      node: 6.9.4
      condition: "$INTEGRATION = true"
