language: node_js
node_js:
- '0.10'
before_install:
- npm install -g npm@'>=2.13.5'
- |
  if [ "$TEST_TYPE" != build_website ]; then
    mkdir -p .npm
    export DISPLAY=:99.0
    sh -e /etc/init.d/xvfb start
  fi
script:
- |
  echo "machine github.com login stellar-jenkins password $GITHUB_TOKEN" >~/.netrc
  git config --global user.name "Travis CI"
  git config --global user.email "accounts+github@stellar.org"

  if [ "$TEST_TYPE" = build_website ]; then
    if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = false ]; then
      set -e

      cd website
      npm install
      ./setup.sh
      ./publish.sh
    fi
  else
    gulp test
    gulp build
  fi
env:
#  matrix:
#  - TEST_TYPE=test
#  - TEST_TYPE=build_website
  global:
    # GITHUB_TOKEN
    secure: Pc3DwkXywnOGAhUdBZiUCKjyljzrQzPoqm9EEr+UL2BaeaDniFLCLEkuU+ViiuJBo8oPyOIl7I+d86Mi5q06fQx55+xH7DmiW/aj4qKVB2U6Ghn6A3QWkQuvRB1o8SP7iTYRCX480ULZs6AGrMd9y1PFRx/L93fBrO+J/bOtEmg=
notifications:
  slack:
    secure: CgXxNEQrQ82EatyF/wSdF0P5rXcWPL+fFZ1lb1aBb8RbVt5gwddJ6xWVD/nYSr6tIJvIYHYhoYsIDPENwezIPsesG7kWXerQhydsEcA34JKxzsStd/TmU6Moxuwy6KTN7yzmL6586nSvoAw9TNPgvRkJFkH07asjGIc9Rlaq7/Y=
deploy:
  - provider: npm
    email: npm@stellar.org
    api_key:
      secure: rQ9OjPbd/6yAgjILpYI4cdrPYPEUvEv/aJF1KrT42KlukLn5jrSGVzuhdVCtv2riNOvxkLFQEzv/Q/DhsB2tJ0nhiad/S21IIaqGmvWZjIUKOHUz91ncEcMDqAMKR1tBGjmtA3J25xbbyPBNFwDRsyNbhjWV2F4iS0Xc9f4abyY=
    skip_cleanup: true
    on:
      tags: true
      repo: stellar/js-stellar-lib
  - provider: script
    script: ./bower_publish.sh
    skip_cleanup: true
    on:
      tags: true
      repo: stellar/js-stellar-lib
